@bearer_authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJuYmYiOjE2MjQ3MTc3NjF9.b4kX9uq1JlJW3JI2zH6e7tsAn1jUqSMQW9g9mjtc4Y4
@login_authorization = Basic YWFhYTpwYXNzd29yZA==
# aaaa:password

GET http://localhost/api/token
Authorization: {{login_authorization}}

###
GET http://localhost/api/users
    ?page_num=1
    &per_page=10

###
POST http://localhost/api/users
Authorization: {{bearer_authorization}}

{
    "name": "new user",
    "email": "aaaa1",
    "password": "password"
}

###
GET http://localhost/api/users/1
Authorization: {{bearer_authorization}}

###
GET http://localhost/api/users/2
Authorization: {{bearer_authorization}}

###
PUT http://localhost/api/communities/1/users/1
Authorization: {{bearer_authorization}}

###
