@bearer_authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJuYmYiOjE2MjUxNDk2NDl9.FIHNyJtApaGHuFFhBbvcr0zutikmGvbdAEbe52BbCRE
@login_authorization = Basic YWRtaW5AYWRtaW46cGFzc3dvcmQ=
# admin@admin:password

GET http://localhost/api/token
Authorization: {{login_authorization}}

###
GET http://localhost/api/users
    ?page_num=1
    &per_page=10

###
POST http://localhost/api/users
Authorization: {{bearer_authorization}}
Content-Type: application/json

{
    "name": "new user",
    "email": "aaaa1",
    "password": "password"
}

###
GET http://localhost/api/users/1
Authorization: {{bearer_authorization}}

###
GET http://localhost/ac/users?method=GET&method=POST
Authorization: {{bearer_authorization}}

###
