@api = http://localhost/api

@bearer_authorization = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJuYmYiOjE2MjUxNDk2NDl9.FIHNyJtApaGHuFFhBbvcr0zutikmGvbdAEbe52BbCRE
@login_authorization = Basic YWRtaW5AYWRtaW46cGFzc3dvcmQ=
# admin@admin:password


###
POST http://localhost/api/create_db

###
POST {{api}}/auth/login
Authorization: {{login_authorization}}

###
POST {{api}}/auth/update
Content-Type: application/json

{
	"token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXBkYXRlZF9hdCI6MTYzNDg5ODg4NCwidXNlcl9pZCI6MSwiY3JlYXRlZF9hdCI6MTYzNDg5ODI5NX0.HBdPA_X95w2FWiSPiOrXW2CaBWUFCDCWXfbt28Dfsuo"
}
###
GET {{api}}/auth/quick
###
GET {{api}}/auth/quick?key=0644ada2bc46142c2e8a30b1b36af63d

###
POST {{api}}/auth/quick?user_id=1&key=0644ada2bc46142c2e8a30b1b36af63d


###
GET {{api}}/users
    ?page_num=1
    &per_page=10

###
POST {{api}}/users
Authorization: {{bearer_authorization}}
Content-Type: application/json

{
	"name": "new user",
    "email": "aaaa1",
    "password": "password"
}

###
GET {{api}}/users/1
Authorization: {{bearer_authorization}}

###
GET {{api}}/communities/1/users
###
PUT {{api}}/communities/1/users/1
###
PUT {{api}}/communities/1/users/1?invitation=1
###
DELETE {{api}}/api/communities/1/users/1
###
PUT {{api}}/communities/1/inputmodes/4key
###
POST {{api}}/roles
Content-Type: application/json

{
	"roletype": "moderator",
	"user_id": 22,
	"leaderboard_id": 99
}
###
POST {{api}}/roles
Content-Type: application/json

{
	"roletype": "moderator",
	"user_id": 22
}
###
DELETE {{api}}/roles
Content-Type: application/json

{
	"roletype": "moderator",
	"user_id": 22,
	"leaderboard_id": 99
}
###

GET {{api}}/users/22/roles
###

GET {{api}}/users/1/rivals
###
PUT {{api}}/users/1/rivals/2
###
PUT {{api}}/users/2/rivals/1
###
DELETE {{api}}/users/1/rivals/2
###